#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src_root="$repo_root/build-clap/plugins"
dst_root="${1:-$HOME/Library/Audio/Plug-Ins/CLAP}"

mkdir -p "$dst_root"

copy_bundle() {
  local bundle="$1"
  local name
  name="$(basename "$bundle")"
  rm -rf "$dst_root/$name"
  cp -R "$bundle" "$dst_root/$name"
}

remove_stale_bundle() {
  local name="$1"
  rm -rf "$dst_root/$name"
}

remove_stale_bundle "s3g_loop_field.clap"
remove_stale_bundle "s3g_utility_delay.clap"
remove_stale_bundle "s3g_modal_terrain.clap"
remove_stale_bundle "s3g_resonant_terrain.clap"
remove_stale_bundle "s3g_string_terrain.clap"
remove_stale_bundle "s3g_3oafx_spatial_grains.clap"
remove_stale_bundle "s3g_3oafx_boundary.clap"
remove_stale_bundle "s3g_3oafx_rack.clap"
remove_stale_bundle "s3g_multi_loop_processor.clap"
remove_stale_bundle "s3g_ambi_grain_processor.clap"
remove_stale_bundle "s3g_3oafx_spectral_spray.clap"
remove_stale_bundle "s3g_3oafx_spectral_smear.clap"
remove_stale_bundle "s3g_node_track_mixer.clap"
remove_stale_bundle "s3g_ambi_node_track_mixer.clap"

copy_bundle "$src_root/clap_24ch_passthrough/s3g_24ch_passthrough_test.clap"
copy_bundle "$src_root/clap_delay_processor/s3g_8ch_delay_processor.clap"
copy_bundle "$src_root/clap_delay_processor/s3g_24ch_delay_processor.clap"
copy_bundle "$src_root/clap_mc_to_stereo_autogain/s3g_mc_to_stereo_autogain.clap"
copy_bundle "$src_root/clap_mc_to_quad_autogain/s3g_mc_to_quad_autogain.clap"
copy_bundle "$src_root/clap_3oafx_single_effects/s3g_3oafx_delay.clap"
copy_bundle "$src_root/clap_3oafx_single_effects/s3g_3oafx_pitch.clap"
copy_bundle "$src_root/clap_3oafx_single_effects/s3g_3oafx_filter.clap"
copy_bundle "$src_root/clap_3oafx_single_effects/s3g_3oafx_gain.clap"
copy_bundle "$src_root/clap_3oafx_point_encoder/s3g_3oafx_point_encoder.clap"
copy_bundle "$src_root/clap_3oafx_speaker_decoder/s3g_3oafx_speaker_decoder.clap"
copy_bundle "$src_root/clap_layout_panner/s3g_layout_panner.clap"
copy_bundle "$src_root/clap_sub_crossover/s3g_sub_crossover.clap"
copy_bundle "$src_root/clap_loop_processor/s3g_loop_processor.clap"
copy_bundle "$src_root/clap_multi_loop_processor/s3g_multi_loop_processor.clap"
copy_bundle "$src_root/clap_ambi_grain_processor/s3g_ambi_grain_processor.clap"
copy_bundle "$src_root/clap_macro_delay/s3g_macro_delay.clap"
copy_bundle "$src_root/clap_macro_delay/s3g_24ch_macro_delay.clap"
copy_bundle "$src_root/clap_macro_pitch/s3g_macro_pitch.clap"
copy_bundle "$src_root/clap_macro_pitch/s3g_24ch_macro_pitch.clap"
copy_bundle "$src_root/clap_buffer_processor/s3g_buffer_processor.clap"
copy_bundle "$src_root/clap_wave_geometry_processor/s3g_wave_geometry_processor.clap"
copy_bundle "$src_root/clap_multichannel_meter/s3g_multichannel_meter.clap"
copy_bundle "$src_root/clap_ambisonic_energy_visualizer/s3g_ambisonic_energy_visualizer.clap"
copy_bundle "$src_root/clap_ambisonic_stereo_decoder/s3g_ambisonic_stereo_decoder.clap"
copy_bundle "$src_root/clap_ambisonic_head_decoder/s3g_ambisonic_head_decoder.clap"
copy_bundle "$src_root/clap_ambisonic_sub_decoder/s3g_ambisonic_sub_decoder.clap"
copy_bundle "$src_root/clap_array_hpf/s3g_array_hpf_16.clap"
copy_bundle "$src_root/clap_array_hpf/s3g_array_hpf_32.clap"
copy_bundle "$src_root/clap_array_hpf/s3g_array_hpf_64.clap"
copy_bundle "$src_root/clap_ambisonic_rotate/s3g_ambisonic_rotate.clap"
copy_bundle "$src_root/clap_ambi_group_rotate/s3g_ambi_group_rotate_64.clap"
copy_bundle "$src_root/clap_ambi_group_rotate/s3g_ambi_group_rotate_128.clap"
copy_bundle "$src_root/clap_ambi_group_depth/s3g_ambi_depth_16.clap"
copy_bundle "$src_root/clap_ambi_group_depth/s3g_ambi_group_depth_64.clap"
copy_bundle "$src_root/clap_ambi_group_depth/s3g_ambi_group_depth_128.clap"
copy_bundle "$src_root/clap_ambisonic_order_band_tool/s3g_ambisonic_order_band_tool.clap"
copy_bundle "$src_root/clap_ambi_group_matrix/s3g_ambi_group_matrix.clap"
copy_bundle "$src_root/clap_ambi_group_matrix_128/s3g_ambi_group_matrix_128.clap"
copy_bundle "$src_root/clap_group_matrix/s3g_group_matrix.clap"
copy_bundle "$src_root/clap_group_matrix_32/s3g_group_matrix_32.clap"
copy_bundle "$src_root/clap_node_track_mixer/s3g_node_bus_mixer.clap"
copy_bundle "$src_root/clap_node_track_mixer/s3g_ambi_node_bus_mixer.clap"
copy_bundle "$src_root/clap_spectral_spray/s3g_spectral_spray.clap"
copy_bundle "$src_root/clap_8ch_spectral_spray/s3g_8ch_spectral_spray.clap"
copy_bundle "$src_root/clap_spectral_topology_processor/s3g_spectral_topology_processor.clap"
copy_bundle "$src_root/clap_spectral_topology_processor/s3g_24ch_spectral_topology_processor.clap"
copy_bundle "$src_root/clap_shard_scatter/s3g_shard_scatter.clap"
copy_bundle "$src_root/clap_orbit_delay/s3g_orbit_delay.clap"
copy_bundle "$src_root/clap_cascade_taps/s3g_cascade_taps.clap"
