# Consolidated, manifest-complete Windows test package (Ambi Energy excluded).
# Run from the repository with an already configured MinGW Makefiles tree:
#   cmake -P scripts/package-windows-clap-suite.cmake
# Optional: -Dbuild_dir=/absolute/build/path -Dparallel=4 before -P.
# Never installs plugins or overwrites a previous package. Rebuilds every target.
cmake_minimum_required(VERSION 3.20)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED build_dir)
  set(build_dir "${repo}/build-clap-windows-cross")
endif()
get_filename_component(build_dir "${build_dir}" ABSOLUTE)
if(NOT DEFINED parallel)
  set(parallel 4)
endif()
if(NOT parallel MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "parallel must be a positive integer")
endif()
file(READ "${build_dir}/CMakeCache.txt" cache)
foreach(setting S3G_ENABLE_PORTABLE_CLAP_GUI S3G_BUILD_TRACKER_PREVIEW S3G_ENABLE_WORLD BUILD_TESTING)
  if(NOT cache MATCHES "${setting}:BOOL=ON([\r\n]|$)")
    message(FATAL_ERROR "Suite packaging requires ${setting}=ON in the build tree")
  endif()
endforeach()
if(NOT cache MATCHES "CMAKE_BUILD_TYPE:STRING=Release([\r\n]|$)" OR
   NOT cache MATCHES "CMAKE_GENERATOR:INTERNAL=Unix Makefiles([\r\n]|$)")
  message(FATAL_ERROR "This packager requires a Release MinGW Unix Makefiles cross-build")
endif()
find_program(objdump x86_64-w64-mingw32-objdump REQUIRED)
find_program(strip x86_64-w64-mingw32-strip REQUIRED)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
set(name "s3g-dsp-windows-clap-suite-x64-test-${stamp}")
set(staging "${repo}/dist/${name}")
set(archive "${staging}.zip")
set(build_log "${build_dir}/${name}-build.log")
if(EXISTS "${staging}" OR EXISTS "${archive}" OR EXISTS "${build_log}")
  message(FATAL_ERROR "Refusing to overwrite an existing package or build log")
endif()

file(STRINGS "${repo}/scripts/clap-bundles.tsv" rows)
set(sources "")
set(canonicals "")
set(targets "")
set(excluded 0)
set(manifest "# Relative build path\tCanonical filename\tCLAP identifier\tHost name\n")
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 4)
    message(FATAL_ERROR "Malformed CLAP inventory row: ${row}")
  endif()
  list(GET fields 0 relative)
  list(GET fields 1 canonical)
  list(GET fields 2 identifier)
  if(NOT relative MATCHES "^clap_[a-z0-9_]+/s3g_[a-z0-9_]+[.]clap$" OR
     NOT canonical MATCHES "^s3g_[a-z0-9_]+[.]clap$" OR
     NOT identifier MATCHES "^org[.]s3g[.]s3g-dsp[.]")
    message(FATAL_ERROR "Unsafe CLAP inventory row: ${row}")
  endif()
  if(canonical STREQUAL "s3g_analyzer_ambi_energy_64.clap")
    math(EXPR excluded "${excluded} + 1")
    continue()
  endif()
  if(canonical IN_LIST canonicals)
    message(FATAL_ERROR "Duplicate CLAP filename: ${canonical}")
  endif()
  set(source "${build_dir}/plugins/${relative}")
  get_filename_component(folder "${source}" DIRECTORY)
  get_filename_component(filename "${source}" NAME)
  string(REPLACE "." "[.]" filename_regex "${filename}")
  # Resolve actual generated target names, not a guessed naming convention.
  # Several canonical product names intentionally differ from their targets.
  file(GLOB link_files "${folder}/CMakeFiles/*.dir/link.txt")
  set(matches "")
  foreach(link IN LISTS link_files)
    file(READ "${link}" command)
    if(command MATCHES " -o \"?${filename_regex}\"?([ \r\n]|$)")
      get_filename_component(target_dir "${link}" DIRECTORY)
      get_filename_component(target "${target_dir}" NAME_WE)
      list(APPEND matches "${target}")
    endif()
  endforeach()
  list(LENGTH matches count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one configured build target for ${relative}; found ${matches}")
  endif()
  list(APPEND targets ${matches})
  list(APPEND sources "${source}")
  list(APPEND canonicals "${canonical}")
  string(APPEND manifest "${row}\n")
endforeach()
list(LENGTH canonicals plugin_count)
if(NOT excluded EQUAL 1 OR plugin_count LESS 1)
  message(FATAL_ERROR "Expected a nonempty inventory with exactly one Ambi Energy exclusion")
endif()
message(STATUS "Refreshing all ${plugin_count} Windows CLAP targets plus Tracker's integration check")
message(STATUS "Build log: ${build_log}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build_dir}" --parallel "${parallel}"
  --target ${targets} s3g_tracker_windows_clap_smoke
  OUTPUT_FILE "${build_log}" ERROR_FILE "${build_log}" RESULT_VARIABLE build_result)
if(NOT build_result EQUAL 0)
  message(FATAL_ERROR "Windows suite build failed; no package published. See ${build_log}")
endif()

function(validate_pe binary needs_clap)
  execute_process(COMMAND "${objdump}" -p "${binary}" OUTPUT_VARIABLE pe
    ERROR_VARIABLE error RESULT_VARIABLE result)
  if(NOT result EQUAL 0 OR NOT pe MATCHES "pei-x86-64" OR
     pe MATCHES "DLL Name: (libgcc|libstdc[+][+]|libwinpthread)")
    message(FATAL_ERROR "Invalid Windows x64 PE or external compiler runtime: ${binary}\n${error}")
  endif()
  if(needs_clap AND NOT pe MATCHES "clap_entry")
    message(FATAL_ERROR "Missing CLAP export: ${binary}")
  endif()
endfunction()

foreach(source IN LISTS sources)
  validate_pe("${source}" TRUE)
  get_filename_component(folder "${source}" DIRECTORY)
  foreach(font FiraCode-Regular.ttf FiraCode-LICENSE.txt)
    if(NOT EXISTS "${folder}/Resources/Fonts/${font}")
      message(FATAL_ERROR "Missing runtime font resource: ${folder}/Resources/Fonts/${font}")
    endif()
  endforeach()
endforeach()
set(tracker_check "${build_dir}/plugins/clap_tracker/s3g_tracker_windows_clap_smoke.exe")
validate_pe("${tracker_check}" FALSE)
file(MAKE_DIRECTORY "${staging}")
foreach(source canonical IN ZIP_LISTS sources canonicals)
  configure_file("${source}" "${staging}/${canonical}" COPYONLY)
  execute_process(COMMAND "${strip}" --strip-unneeded "${staging}/${canonical}"
    COMMAND_ERROR_IS_FATAL ANY)
  validate_pe("${staging}/${canonical}" TRUE)
  get_filename_component(folder "${source}" DIRECTORY)
  file(GLOB_RECURSE resources LIST_DIRECTORIES FALSE RELATIVE "${folder}/Resources"
    "${folder}/Resources/*")
  foreach(resource IN LISTS resources)
    set(input "${folder}/Resources/${resource}")
    set(output "${staging}/Resources/${resource}")
    if(IS_SYMLINK "${input}")
      message(FATAL_ERROR "Refusing a symlinked resource: ${input}")
    endif()
    if(EXISTS "${output}")
      file(SHA256 "${input}" input_hash)
      file(SHA256 "${output}" output_hash)
      if(NOT input_hash STREQUAL output_hash)
        message(FATAL_ERROR "Conflicting shared resource: ${resource}; use isolated per-plugin folders instead")
      endif()
    else()
      configure_file("${input}" "${output}" COPYONLY)
    endif()
  endforeach()
endforeach()
foreach(font IBMPlexMono-Regular.ttf IBMPlexMono-Medium.ttf IBMPlexMono-SemiBold.ttf OFL.txt)
  if(NOT EXISTS "${staging}/Resources/Fonts/${font}")
    message(FATAL_ERROR "Missing Tracker font/license: ${font}")
  endif()
endforeach()
foreach(atlas "Imprint Atlas|s3gimprint" "Ray Atlas|s3gray")
  string(REPLACE "|" ";" fields "${atlas}")
  list(GET fields 0 folder)
  list(GET fields 1 extension)
  file(GLOB responses "${staging}/Resources/${folder}/*.${extension}")
  list(LENGTH responses count)
  if(NOT count EQUAL 19)
    message(FATAL_ERROR "Expected 19 ${folder} responses; found ${count}")
  endif()
endforeach()
configure_file("${tracker_check}" "${staging}/s3g_tracker_windows_clap_smoke.exe" COPYONLY)
execute_process(COMMAND "${strip}" --strip-unneeded "${staging}/s3g_tracker_windows_clap_smoke.exe"
  COMMAND_ERROR_IS_FATAL ANY)
validate_pe("${staging}/s3g_tracker_windows_clap_smoke.exe" FALSE)
configure_file("${repo}/scripts/run-tracker-windows-check.cmd" "${staging}/run-windows-check.cmd" @ONLY NEWLINE_STYLE CRLF)
configure_file("${repo}/plugins/common/TRACKER_WINDOWS_README.txt" "${staging}/TRACKER-README.txt" COPYONLY)
configure_file("${repo}/plugins/common/WINDOWS_CLAP_SUITE_README.txt" "${staging}/README.txt" @ONLY NEWLINE_STYLE CRLF)
configure_file("${repo}/LICENSE" "${staging}/LICENSE.txt" COPYONLY)
configure_file("${repo}/tracker/LICENSE" "${staging}/TRACKER-LICENSE.txt" COPYONLY)
configure_file("${repo}/THIRD_PARTY_NOTICES.md" "${staging}/THIRD_PARTY_NOTICES.md" COPYONLY)
configure_file("${build_dir}/_deps/vstgui-src/LICENSE" "${staging}/Resources/Licenses/VSTGUI-LICENSE.txt" COPYONLY)
foreach(license RapidJSON-LICENSE.txt WORLD-LICENSE.txt)
  if(NOT EXISTS "${staging}/Resources/Licenses/${license}")
    message(FATAL_ERROR "Missing dependency notice: ${license}")
  endif()
endforeach()
file(WRITE "${staging}/PLUGIN_MANIFEST.tsv" "${manifest}")
file(WRITE "${staging}/EXCLUDED.txt" "s3g_analyzer_ambi_energy_64.clap\tAmbi Energy renderer prototype is not a Windows CLAP; plugin integration and acceptance remain pending.\n")
set(provenance "Source SHA256 at packaging: current worktree, not a release tag.\n")
foreach(folder plugins tracker dsp cmake)
  file(GLOB_RECURSE inputs LIST_DIRECTORIES FALSE
    "${repo}/${folder}/*.cpp" "${repo}/${folder}/*.h" "${repo}/${folder}/*.hpp"
    "${repo}/${folder}/*.mm" "${repo}/${folder}/*.inc" "${repo}/${folder}/*.cmake"
    "${repo}/${folder}/CMakeLists.txt")
  list(APPEND source_files ${inputs})
endforeach()
list(APPEND source_files "${repo}/CMakeLists.txt" "${repo}/CMakePresets.json"
  "${repo}/scripts/clap-bundles.tsv" "${CMAKE_CURRENT_LIST_FILE}")
list(SORT source_files)
foreach(source IN LISTS source_files)
  file(SHA256 "${source}" hash)
  file(RELATIVE_PATH relative "${repo}" "${source}")
  string(APPEND provenance "${hash}  ${relative}\n")
endforeach()
file(WRITE "${staging}/SOURCE_PROVENANCE.txt" "${provenance}")
file(GLOB packaged_claps "${staging}/*.clap")
list(LENGTH packaged_claps count)
if(NOT count EQUAL plugin_count)
  message(FATAL_ERROR "Final package count differs from canonical inventory")
endif()
file(GLOB_RECURSE payload LIST_DIRECTORIES FALSE RELATIVE "${staging}" "${staging}/*")
list(SORT payload)
set(sums "")
foreach(relative IN LISTS payload)
  file(SHA256 "${staging}/${relative}" hash)
  string(APPEND sums "${hash}  ${relative}\n")
endforeach()
file(WRITE "${staging}/SHA256SUMS.txt" "${sums}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip "${name}"
  WORKING_DIRECTORY "${repo}/dist" COMMAND_ERROR_IS_FATAL ANY)
file(SHA256 "${archive}" archive_hash)
file(WRITE "${archive}.sha256" "${archive_hash}  ${name}.zip\n")
message(STATUS "Packaged ${plugin_count} Windows x64 CLAPs; only Ambi Energy excluded")
message(STATUS "Folder: ${staging}")
message(STATUS "ZIP: ${archive}")
message(STATUS "SHA256: ${archive_hash}")
message(STATUS "Cross-build/package validation only; native Windows/REAPER testing remains required")
