# Package only the standalone renderer experiment; never install or ship a CLAP.
cmake_minimum_required(VERSION 3.20)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED build_dir)
  set(build_dir "${repo}/build-ambi-energy-probe-windows")
endif()
if(NOT DEFINED input_file)
  set(input_file "${repo}/build-ambi-energy-probe-mac/input.bin")
endif()
if(NOT DEFINED reference_file)
  set(reference_file "${repo}/build-ambi-energy-probe-mac/metal-reference.bin")
endif()
if(NOT DEFINED record_report)
  set(record_report "${repo}/build-ambi-energy-probe-mac/record/report.txt")
endif()
if(NOT DEFINED compare_report)
  set(compare_report "${repo}/build-ambi-energy-probe-mac/compare/report.txt")
endif()
if(NOT DEFINED host_probe)
  set(host_probe "${repo}/build-ambi-energy-probe-mac/s3g_ambi_energy_renderer_probe")
endif()
execute_process(COMMAND "${host_probe}" --check-files "${input_file}" "${reference_file}"
  OUTPUT_VARIABLE input_check ERROR_VARIABLE check_error RESULT_VARIABLE check_result)
if(NOT check_result EQUAL 0)
  message(FATAL_ERROR "Fixture/reference validation failed: ${check_error}")
endif()
string(REGEX MATCH "Input fingerprint [(]FNV-1a64[)]: [0-9a-f]+" fingerprint "${input_check}")
if(fingerprint STREQUAL "")
  message(FATAL_ERROR "Missing input fingerprint")
endif()
foreach(report "${record_report}" "${compare_report}")
  file(READ "${report}" contents)
  string(FIND "${contents}" "${fingerprint}" fingerprint_at)
  if(fingerprint_at LESS 0 OR contents MATCHES "FAIL|ERROR" OR NOT contents MATCHES "PASS: 49 frames checked.[\r\n]*$")
    message(FATAL_ERROR "A successful 49-frame Mac record/replay report is required: ${report}")
  endif()
endforeach()
find_program(objdump x86_64-w64-mingw32-objdump REQUIRED)
find_program(strip x86_64-w64-mingw32-strip REQUIRED)
set(exe "${build_dir}/s3g_ambi_energy_renderer_probe.exe")
execute_process(COMMAND "${objdump}" -p "${exe}" RESULT_VARIABLE status OUTPUT_VARIABLE pe ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT pe MATCHES "pei-x86-64" OR NOT pe MATCHES "DLL Name: d3d11.dll"
    OR NOT pe MATCHES "D3DCOMPILER_47.dll" OR pe MATCHES "DLL Name: (libgcc|libstdc[+][+]|libwinpthread)")
  message(FATAL_ERROR "Invalid Windows renderer executable or external MinGW runtime: ${error}")
endif()
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
set(name "s3g-ambi-energy-windows-renderer-prototype-x64-${stamp}")
set(staging "${repo}/dist/${name}")
if(EXISTS "${staging}" OR EXISTS "${staging}.zip")
  message(FATAL_ERROR "Refusing to overwrite an existing test package")
endif()
file(MAKE_DIRECTORY "${staging}")
configure_file("${exe}" "${staging}/s3g_ambi_energy_renderer_probe.exe" COPYONLY)
execute_process(COMMAND "${strip}" --strip-unneeded "${staging}/s3g_ambi_energy_renderer_probe.exe" COMMAND_ERROR_IS_FATAL ANY)
configure_file("${input_file}" "${staging}/input.bin" COPYONLY)
configure_file("${reference_file}" "${staging}/metal-reference.bin" COPYONLY)
configure_file("${record_report}" "${staging}/mac-record-report.txt" COPYONLY)
configure_file("${compare_report}" "${staging}/mac-replay-report.txt" COPYONLY)
configure_file("${repo}/tests/ambi_energy_renderer/WINDOWS_README.txt" "${staging}/README.txt" COPYONLY)
configure_file("${repo}/LICENSE" "${staging}/LICENSE.txt" COPYONLY)
configure_file("${repo}/THIRD_PARTY_NOTICES.md" "${staging}/THIRD_PARTY_NOTICES.md" COPYONLY)
foreach(script run-test.cmd run-software-test.cmd)
  configure_file("${repo}/tests/ambi_energy_renderer/${script}" "${staging}/${script}" @ONLY NEWLINE_STYLE CRLF)
endforeach()
set(provenance "Source SHA256 at packaging (source files are in the repository):\n")
file(GLOB renderer_sources "${repo}/plugins/clap_ambisonic_energy_visualizer/renderer/*")
list(APPEND renderer_sources "${repo}/tests/ambi_energy_renderer/probe.cpp" "${repo}/tests/ambi_energy_renderer/CMakeLists.txt")
foreach(source IN LISTS renderer_sources)
  file(SHA256 "${source}" hash)
  file(RELATIVE_PATH relative "${repo}" "${source}")
  string(APPEND provenance "${hash}  ${relative}\n")
endforeach()
file(WRITE "${staging}/SOURCE_PROVENANCE.txt" "${provenance}")
file(GLOB payload LIST_DIRECTORIES FALSE RELATIVE "${staging}" "${staging}/*")
list(SORT payload)
set(sums "")
foreach(relative IN LISTS payload)
  file(SHA256 "${staging}/${relative}" hash)
  string(APPEND sums "${hash}  ${relative}\n")
endforeach()
file(WRITE "${staging}/SHA256SUMS.txt" "${sums}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${staging}.zip" --format=zip "${name}"
  WORKING_DIRECTORY "${repo}/dist" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Windows prototype folder: ${staging}")
message(STATUS "Windows prototype ZIP: ${staging}.zip")
