# Package already-built Windows test binaries without changing installations.
# cmake -P scripts/package-windows-environment-encoders.cmake
cmake_minimum_required(VERSION 3.20)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED build_dir)
  set(build_dir "${repo}/build-clap-windows-cross")
endif()
find_program(objdump x86_64-w64-mingw32-objdump REQUIRED)
find_program(strip x86_64-w64-mingw32-strip REQUIRED)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
set(package_name "s3g-dsp-windows-environment-encoders-x64-${stamp}")
set(staging "${repo}/dist/${package_name}")
if(EXISTS "${staging}")
  message(FATAL_ERROR "Refusing to overwrite existing package: ${staging}")
endif()
set(names wind water insect cryosphere pyrosphere)
foreach(name IN LISTS names)
  set(binary "${build_dir}/plugins/clap_ambi_${name}_encoder/s3g_ambi_${name}_encoder.clap")
  execute_process(COMMAND "${objdump}" -p "${binary}" OUTPUT_VARIABLE pe
    RESULT_VARIABLE result ERROR_VARIABLE error)
  if(NOT result EQUAL 0 OR NOT pe MATCHES "pei-x86-64" OR NOT pe MATCHES "clap_entry"
      OR pe MATCHES "DLL Name: (libgcc|libstdc[+][+]|libwinpthread)")
    message(FATAL_ERROR "Invalid Windows CLAP or external MinGW runtime: ${binary}\n${error}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${staging}/Resources/Fonts")
set(sums "")
foreach(name IN LISTS names)
  set(source "${build_dir}/plugins/clap_ambi_${name}_encoder/s3g_ambi_${name}_encoder.clap")
  set(target "s3g_ambi_encoder_${name}_64.clap")
  configure_file("${source}" "${staging}/${target}" COPYONLY)
  execute_process(COMMAND "${strip}" --strip-unneeded "${staging}/${target}"
    COMMAND_ERROR_IS_FATAL ANY)
  file(SHA256 "${staging}/${target}" hash)
  string(APPEND sums "${hash}  ${target}\n")
endforeach()
foreach(font FiraCode-Regular.ttf FiraCode-LICENSE.txt)
  configure_file("${repo}/assets/fonts/${font}" "${staging}/Resources/Fonts/${font}" COPYONLY)
  file(SHA256 "${staging}/Resources/Fonts/${font}" hash)
  string(APPEND sums "${hash}  Resources/Fonts/${font}\n")
endforeach()
configure_file("${repo}/LICENSE" "${staging}/LICENSE.txt" COPYONLY)
configure_file("${repo}/THIRD_PARTY_NOTICES.md" "${staging}/THIRD_PARTY_NOTICES.md" COPYONLY)
configure_file("${repo}/plugins/common/ENVIRONMENT_ENCODERS_WINDOWS_README.txt" "${staging}/README.txt" COPYONLY)
file(WRITE "${staging}/SHA256SUMS.txt" "${sums}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${staging}.zip" --format=zip "${package_name}"
  WORKING_DIRECTORY "${repo}/dist" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Windows folder: ${staging}")
message(STATUS "Windows archive: ${staging}.zip")
