# Package the exact scoped rollout, including each plugin's runtime resources.
# cmake -P scripts/package-windows-vstgui-menu-rollout.cmake
cmake_minimum_required(VERSION 3.20)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED build_dir)
  set(build_dir "${repo}/build-clap-windows-cross")
endif()
set(manifest "${repo}/scripts/clap-vstgui-menu-rollout.tsv")
find_program(objdump x86_64-w64-mingw32-objdump REQUIRED)
find_program(strip x86_64-w64-mingw32-strip REQUIRED)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
set(package_name "s3g-dsp-windows-vstgui-menu-parity-x64-${stamp}")
set(staging "${repo}/dist/${package_name}")
if(EXISTS "${staging}" OR EXISTS "${staging}.zip")
  message(FATAL_ERROR "Refusing to overwrite an existing package: ${staging}")
endif()
file(STRINGS "${manifest}" rows)
set(sources "")
set(targets "")
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 4)
    message(FATAL_ERROR "Malformed manifest row: ${row}")
  endif()
  list(GET fields 0 relative)
  list(GET fields 1 target)
  if(NOT relative MATCHES "^clap_[a-z0-9_]+/s3g_[a-z0-9_]+[.]clap$"
      OR NOT target MATCHES "^s3g_[a-z0-9_]+[.]clap$")
    message(FATAL_ERROR "Unsafe manifest path: ${row}")
  endif()
  if(target IN_LIST targets)
    message(FATAL_ERROR "Duplicate target: ${target}")
  endif()
  set(source "${build_dir}/plugins/${relative}")
  execute_process(COMMAND "${objdump}" -p "${source}" OUTPUT_VARIABLE pe
    RESULT_VARIABLE result ERROR_VARIABLE error)
  if(NOT result EQUAL 0 OR NOT pe MATCHES "pei-x86-64" OR NOT pe MATCHES "clap_entry"
      OR pe MATCHES "DLL Name: (libgcc|libstdc[+][+]|libwinpthread)")
    message(FATAL_ERROR "Invalid Windows CLAP or external MinGW runtime: ${source}\n${error}")
  endif()
  get_filename_component(folder "${source}" DIRECTORY)
  foreach(font FiraCode-Regular.ttf FiraCode-LICENSE.txt)
    if(NOT EXISTS "${folder}/Resources/Fonts/${font}")
      message(FATAL_ERROR "Missing font resource: ${folder}/Resources/Fonts/${font}")
    endif()
  endforeach()
  list(APPEND sources "${source}")
  list(APPEND targets "${target}")
endforeach()
list(LENGTH targets count)
if(NOT count EQUAL 36)
  message(FATAL_ERROR "Expected the complete 36-plugin rollout; got ${count}")
endif()
file(MAKE_DIRECTORY "${staging}")
foreach(source target IN ZIP_LISTS sources targets)
  configure_file("${source}" "${staging}/${target}" COPYONLY)
  execute_process(COMMAND "${strip}" --strip-unneeded "${staging}/${target}"
    COMMAND_ERROR_IS_FATAL ANY)
  get_filename_component(folder "${source}" DIRECTORY)
  file(GLOB_RECURSE resources LIST_DIRECTORIES FALSE RELATIVE "${folder}/Resources"
    "${folder}/Resources/*")
  foreach(resource IN LISTS resources)
    set(destination "${staging}/Resources/${resource}")
    if(EXISTS "${destination}")
      file(SHA256 "${folder}/Resources/${resource}" source_hash)
      file(SHA256 "${destination}" target_hash)
      if(NOT source_hash STREQUAL target_hash)
        message(FATAL_ERROR "Conflicting shared resource: ${resource}")
      endif()
    else()
      configure_file("${folder}/Resources/${resource}" "${destination}" COPYONLY)
    endif()
  endforeach()
endforeach()
configure_file("${manifest}" "${staging}/PLUGIN_MANIFEST.tsv" COPYONLY)
configure_file("${repo}/LICENSE" "${staging}/LICENSE.txt" COPYONLY)
configure_file("${repo}/THIRD_PARTY_NOTICES.md" "${staging}/THIRD_PARTY_NOTICES.md" COPYONLY)
configure_file("${build_dir}/_deps/vstgui-src/LICENSE"
  "${staging}/Resources/Licenses/VSTGUI-LICENSE.txt" COPYONLY)
configure_file("${repo}/plugins/common/VSTGUI_MENU_WINDOWS_README.txt"
  "${staging}/README.txt" COPYONLY)
file(GLOB_RECURSE packaged LIST_DIRECTORIES FALSE RELATIVE "${staging}" "${staging}/*")
list(SORT packaged)
set(sums "")
foreach(path IN LISTS packaged)
  file(SHA256 "${staging}/${path}" hash)
  string(APPEND sums "${hash}  ${path}\n")
endforeach()
file(WRITE "${staging}/SHA256SUMS.txt" "${sums}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${staging}.zip" --format=zip "${package_name}"
  WORKING_DIRECTORY "${repo}/dist" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Packaged ${count} Windows x64 CLAP plugins with all resources")
message(STATUS "Windows folder: ${staging}")
message(STATUS "Windows archive: ${staging}.zip")
