if(S3G_AMBI_EFFECTS_VSTGUI_AVAILABLE AND BUILD_TESTING AND S3G_BUILD_CLAP_PLUGIN)
  function(s3g_ambi_effect_canvas_test name source family)
    set(target "s3g_ambi_effect_${name}_canvas_smoke")
    add_executable(${target} "${PROJECT_SOURCE_DIR}/tests/ambi_effect_canvas_smoke.cpp")
    target_link_libraries(${target} PRIVATE s3g_dsp)
    target_include_directories(${target} PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE
      "S3G_TEST_ROUTING_SOURCE=\"../plugins/clap_ambi_effect_${source}/s3g_ambi_effect_${source}_clap.cpp\""
      S3G_TEST_ROUTING_EDITOR=ambi_effect_canvas::Editor S3G_ROUTING_FAMILY=8
      S3G_TEST_OUTPUT_PARAM=kParamOutput S3G_EFFECT_FAMILY=${family} ${ARGN})
    s3g_enable_vstgui_gui(${target}
      "${PROJECT_SOURCE_DIR}/plugins/common/s3g_ambi_effect_${source}_canvas.inc"
      S3G_ENABLE_VSTGUI_CANVAS_GUI)
    if(APPLE)
      set_source_files_properties("${PROJECT_SOURCE_DIR}/tests/ambi_effect_canvas_smoke.cpp"
        PROPERTIES LANGUAGE OBJCXX)
      set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
      target_link_libraries(${target} PRIVATE "-framework Cocoa")
    endif()
    add_test(NAME ${target} COMMAND $<TARGET_FILE:${target}>)
    set_tests_properties(${target} PROPERTIES LABELS "non_nim;ambi_effect;gui;smoke" TIMEOUT 180)
  endfunction()
  s3g_ambi_effect_canvas_test(dj_filter dj_filter 0)
  s3g_ambi_effect_canvas_test(delay delay 1)
  s3g_ambi_effect_canvas_test(pitch pitch_gain 2 S3G_AMBI_EFFECT_PITCH=1)
  s3g_ambi_effect_canvas_test(gain pitch_gain 2 S3G_AMBI_EFFECT_PITCH=0)
  s3g_ambi_effect_canvas_test(resonance_print resonance_print 3)
  s3g_ambi_effect_canvas_test(partial_trace trace 4 S3G_PARTIAL_TRACE=1)
  s3g_ambi_effect_canvas_test(response_trace trace 4 S3G_PARTIAL_TRACE=0)
  s3g_ambi_effect_canvas_test(displacement displacement 5)
endif()

if(BUILD_TESTING)
  add_executable(s3g_ambi_effect_capture_snapshot_smoke
    "${PROJECT_SOURCE_DIR}/tests/ambi_effect_capture_snapshot_smoke.cpp")
  target_link_libraries(s3g_ambi_effect_capture_snapshot_smoke PRIVATE s3g_dsp)
  add_test(NAME s3g_ambi_effect_capture_snapshot_smoke COMMAND s3g_ambi_effect_capture_snapshot_smoke)
  set_tests_properties(s3g_ambi_effect_capture_snapshot_smoke PROPERTIES LABELS "non_nim;ambi_effect;smoke")
  add_executable(s3g_ambi_effect_fft_smoke "${PROJECT_SOURCE_DIR}/tests/ambi_effect_fft_smoke.cpp")
  target_link_libraries(s3g_ambi_effect_fft_smoke PRIVATE s3g_dsp)
  if(APPLE)
    target_link_libraries(s3g_ambi_effect_fft_smoke PRIVATE "-framework Accelerate")
  endif()
  add_test(NAME s3g_ambi_effect_fft_smoke COMMAND s3g_ambi_effect_fft_smoke)
  set_tests_properties(s3g_ambi_effect_fft_smoke PROPERTIES LABELS "non_nim;ambi_effect;smoke")
  foreach(engine IN ITEMS resonance_print trace)
    add_executable(s3g_ambi_effect_${engine}_portable_fft_smoke
      "${PROJECT_SOURCE_DIR}/tests/ambi_effect_${engine}_smoke.cpp")
    target_link_libraries(s3g_ambi_effect_${engine}_portable_fft_smoke PRIVATE s3g_dsp)
    target_compile_definitions(s3g_ambi_effect_${engine}_portable_fft_smoke PRIVATE S3G_FORCE_PORTABLE_AMBI_FFT=1)
    add_test(NAME s3g_ambi_effect_${engine}_portable_fft_smoke COMMAND s3g_ambi_effect_${engine}_portable_fft_smoke)
    set_tests_properties(s3g_ambi_effect_${engine}_portable_fft_smoke PROPERTIES LABELS "non_nim;ambi_effect;smoke" TIMEOUT 180)
  endforeach()
endif()
