if(S3G_COMPLEX_PROCESSORS_VSTGUI_AVAILABLE AND BUILD_TESTING AND S3G_BUILD_CLAP_PLUGIN)
  set(kind 0)
  foreach(pair "imprint|ambi_imprint" "formant|acapella_source_synth" "nim|no_input_mixer" "vox|ambi_vox_encoder")
    math(EXPR kind "${kind}+1")
    string(REPLACE "|" ";" fields "${pair}")
    list(GET fields 0 name)
    list(GET fields 1 wrapper)
    set(target s3g_complex_${name}_canvas_smoke)
    add_executable(${target} "${PROJECT_SOURCE_DIR}/tests/complex_processor_canvas_smoke.cpp")
    target_link_libraries(${target} PRIVATE s3g_dsp)
    target_include_directories(${target} PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE S3G_COMPLEX_KIND=${kind}
      "S3G_COMPLEX_SOURCE=\"../plugins/clap_${wrapper}/s3g_${wrapper}_clap.cpp\""
      "S3G_TEST_REPO=\"${PROJECT_SOURCE_DIR}\"")
    s3g_enable_vstgui_gui(${target}
      "${PROJECT_SOURCE_DIR}/plugins/common/s3g_complex_processor_${name}_canvas.inc"
      S3G_ENABLE_VSTGUI_CANVAS_GUI)
    if(name STREQUAL "vox" AND TARGET world::core)
      target_link_libraries(${target} PRIVATE world::core)
      target_compile_definitions(${target} PRIVATE S3G_HAS_WORLD=1)
    endif()
    if(APPLE)
      set_source_files_properties("${PROJECT_SOURCE_DIR}/tests/complex_processor_canvas_smoke.cpp" PROPERTIES LANGUAGE OBJCXX)
      set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
      target_link_libraries(${target} PRIVATE "-framework Cocoa" "-framework Accelerate")
    endif()
    add_test(NAME ${target} COMMAND $<TARGET_FILE:${target}>)
    set_tests_properties(${target} PROPERTIES LABELS "complex;gui;smoke" TIMEOUT 300)
  endforeach()
  add_executable(s3g_ambi_imprint_portable_fft_smoke "${PROJECT_SOURCE_DIR}/tests/ambi_imprint_safety_smoke.cpp")
  target_link_libraries(s3g_ambi_imprint_portable_fft_smoke PRIVATE s3g_dsp)
  target_compile_definitions(s3g_ambi_imprint_portable_fft_smoke PRIVATE S3G_FORCE_PORTABLE_AMBI_FFT=1)
  add_test(NAME s3g_ambi_imprint_portable_fft_smoke COMMAND $<TARGET_FILE:s3g_ambi_imprint_portable_fft_smoke>)
  if(APPLE)
    add_executable(s3g_complex_processor_clap_parity_smoke "${PROJECT_SOURCE_DIR}/tests/complex_processor_clap_parity_smoke.cpp")
    target_include_directories(s3g_complex_processor_clap_parity_smoke PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_features(s3g_complex_processor_clap_parity_smoke PRIVATE cxx_std_17)
    target_link_libraries(s3g_complex_processor_clap_parity_smoke PRIVATE ${CMAKE_DL_LIBS})
    add_executable(s3g_complex_vox_portable_fft_smoke "${PROJECT_SOURCE_DIR}/tests/complex_processor_canvas_smoke.cpp")
    target_link_libraries(s3g_complex_vox_portable_fft_smoke PRIVATE s3g_dsp "-framework Cocoa" "-framework Accelerate")
    target_include_directories(s3g_complex_vox_portable_fft_smoke PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(s3g_complex_vox_portable_fft_smoke PRIVATE S3G_COMPLEX_KIND=4 S3G_FORCE_PORTABLE_AMBI_FFT=1
      "S3G_COMPLEX_SOURCE=\"../plugins/clap_ambi_vox_encoder/s3g_ambi_vox_encoder_clap.cpp\"" "S3G_TEST_REPO=\"${PROJECT_SOURCE_DIR}\"")
    if(TARGET world::core)
      target_link_libraries(s3g_complex_vox_portable_fft_smoke PRIVATE world::core)
      target_compile_definitions(s3g_complex_vox_portable_fft_smoke PRIVATE S3G_HAS_WORLD=1)
    endif()
    set_target_properties(s3g_complex_vox_portable_fft_smoke PROPERTIES MACOSX_BUNDLE TRUE)
    s3g_enable_vstgui_gui(s3g_complex_vox_portable_fft_smoke "${PROJECT_SOURCE_DIR}/plugins/common/s3g_complex_processor_vox_canvas.inc" S3G_ENABLE_VSTGUI_CANVAS_GUI)
    add_test(NAME s3g_complex_vox_portable_fft_smoke COMMAND $<TARGET_FILE:s3g_complex_vox_portable_fft_smoke>)
    set_tests_properties(s3g_complex_vox_portable_fft_smoke PROPERTIES LABELS "complex;gui;smoke" TIMEOUT 300)
  endif()
endif()
