if(S3G_ENVIRONMENT_ENCODERS_VSTGUI_AVAILABLE AND BUILD_TESTING AND S3G_BUILD_CLAP_PLUGIN)
  foreach(name wind water insect cryosphere pyrosphere)
    set(target s3g_environment_${name}_canvas_smoke)
    add_executable(${target} "${PROJECT_SOURCE_DIR}/tests/environment_encoder_canvas_smoke.cpp")
    target_link_libraries(${target} PRIVATE s3g_dsp)
    target_include_directories(${target} PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE
      "S3G_ENVIRONMENT_SOURCE=\"../plugins/clap_ambi_${name}_encoder/s3g_ambi_${name}_encoder_clap.cpp\"")
    s3g_enable_vstgui_gui(${target}
      "${PROJECT_SOURCE_DIR}/plugins/common/s3g_environment_encoder_${name}_canvas.inc"
      S3G_ENABLE_VSTGUI_CANVAS_GUI)
    if(APPLE)
      set_source_files_properties("${PROJECT_SOURCE_DIR}/tests/environment_encoder_canvas_smoke.cpp" PROPERTIES LANGUAGE OBJCXX)
      set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
      target_link_libraries(${target} PRIVATE "-framework Cocoa")
    endif()
    add_test(NAME ${target} COMMAND $<TARGET_FILE:${target}>)
    set_tests_properties(${target} PROPERTIES LABELS "non_nim;encoder;gui;smoke" TIMEOUT 180)
  endforeach()
  if(APPLE)
    add_executable(s3g_environment_clap_parity_smoke "${PROJECT_SOURCE_DIR}/tests/environment_encoder_clap_parity_smoke.cpp")
    target_include_directories(s3g_environment_clap_parity_smoke PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_features(s3g_environment_clap_parity_smoke PRIVATE cxx_std_17)
  endif()
endif()
