if(S3G_MIDI_TOOLS_VSTGUI_AVAILABLE AND BUILD_TESTING AND S3G_BUILD_CLAP_PLUGIN)
  foreach(name nim_gesture relay)
    set(wrapper ${name})
    set(target s3g_midi_${name}_canvas_smoke)
    add_executable(${target} "${PROJECT_SOURCE_DIR}/tests/midi_tool_canvas_smoke.cpp")
    target_link_libraries(${target} PRIVATE s3g_dsp)
    target_include_directories(${target} PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE
      "S3G_MIDI_SOURCE=\"../plugins/clap_${wrapper}/s3g_${wrapper}_clap.cpp\"")
    s3g_enable_vstgui_gui(${target}
      "${PROJECT_SOURCE_DIR}/plugins/common/s3g_midi_tool_${name}_canvas.inc"
      S3G_ENABLE_VSTGUI_CANVAS_GUI)
    if(APPLE)
      set_source_files_properties("${PROJECT_SOURCE_DIR}/tests/midi_tool_canvas_smoke.cpp" PROPERTIES LANGUAGE OBJCXX)
      set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
      target_link_libraries(${target} PRIVATE "-framework Cocoa")
    endif()
    add_test(NAME ${target} COMMAND $<TARGET_FILE:${target}>)
    set_tests_properties(${target} PROPERTIES LABELS "midi;gui;smoke" TIMEOUT 180)
  endforeach()
  if(APPLE)
    add_executable(s3g_midi_tool_clap_parity_smoke "${PROJECT_SOURCE_DIR}/tests/midi_tool_clap_parity_smoke.cpp")
    target_include_directories(s3g_midi_tool_clap_parity_smoke PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_features(s3g_midi_tool_clap_parity_smoke PRIVATE cxx_std_17)
    target_link_libraries(s3g_midi_tool_clap_parity_smoke PRIVATE ${CMAKE_DL_LIBS})
  endif()
endif()
