if(S3G_MAP_ENCODERS_VSTGUI_AVAILABLE AND BUILD_TESTING AND S3G_BUILD_CLAP_PLUGIN)
  foreach(name surface wave cartography)
    if(name STREQUAL "surface")
      set(wrapper terrain_navigator)
    elseif(name STREQUAL "wave")
      set(wrapper wave_terrain_encoder)
    else()
      set(wrapper cartography_encoder)
    endif()
    set(target s3g_map_${name}_canvas_smoke)
    add_executable(${target} "${PROJECT_SOURCE_DIR}/tests/map_encoder_canvas_smoke.cpp")
    target_link_libraries(${target} PRIVATE s3g_dsp)
    target_include_directories(${target} PRIVATE "${S3G_CLAP_INCLUDE_DIR}")
    target_compile_definitions(${target} PRIVATE
      "S3G_MAP_SOURCE=\"../plugins/clap_ambi_${wrapper}/s3g_ambi_${wrapper}_clap.cpp\"")
    s3g_enable_vstgui_gui(${target}
      "${PROJECT_SOURCE_DIR}/plugins/common/s3g_map_encoder_${name}_canvas.inc"
      S3G_ENABLE_VSTGUI_CANVAS_GUI)
    if(APPLE)
      set_source_files_properties("${PROJECT_SOURCE_DIR}/tests/map_encoder_canvas_smoke.cpp" PROPERTIES LANGUAGE OBJCXX)
      set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
      target_link_libraries(${target} PRIVATE "-framework Cocoa")
    endif()
    add_test(NAME ${target} COMMAND $<TARGET_FILE:${target}>)
    set_tests_properties(${target} PROPERTIES LABELS "non_nim;encoder;gui;smoke" TIMEOUT 180)
  endforeach()
endif()
