# Keep the pinned dependency checkout pristine. Build a corrected copy of its
# Windows text adapter; no other platform compiles this generated source.
if(NOT WIN32)
  return()
endif()
set(s3g_clipboard_original "${vstgui_SOURCE_DIR}/vstgui/lib/platform/win32/win32dragging.cpp")
file(READ "${s3g_clipboard_original}" s3g_clipboard_source)
set(s3g_clipboard_begin "\tif (format->cfFormat == CF_TEXT || format->cfFormat == CF_UNICODETEXT)")
set(s3g_clipboard_end "\telse if (format->cfFormat == CF_HDROP)")
string(FIND "${s3g_clipboard_source}" "${s3g_clipboard_begin}" s3g_clipboard_first)
string(FIND "${s3g_clipboard_source}" "${s3g_clipboard_end}" s3g_clipboard_last)
if(s3g_clipboard_first LESS 0 OR s3g_clipboard_last LESS s3g_clipboard_first)
  message(FATAL_ERROR "Pinned VSTGUI Windows clipboard adapter changed; review the compatibility correction")
endif()
string(SUBSTRING "${s3g_clipboard_source}" 0 ${s3g_clipboard_first} s3g_clipboard_prefix)
string(SUBSTRING "${s3g_clipboard_source}" ${s3g_clipboard_last} -1 s3g_clipboard_suffix)
file(READ "${CMAKE_CURRENT_LIST_DIR}/windows/vstgui_clipboard_text.inc" s3g_clipboard_text)
set(s3g_clipboard_generated "${CMAKE_BINARY_DIR}/s3g-vstgui-windows/win32dragging.cpp")
file(GENERATE OUTPUT "${s3g_clipboard_generated}"
  CONTENT "${s3g_clipboard_prefix}${s3g_clipboard_text}\n${s3g_clipboard_suffix}")
get_target_property(s3g_clipboard_sources vstgui SOURCES)
set(s3g_clipboard_matches ${s3g_clipboard_sources})
list(FILTER s3g_clipboard_matches INCLUDE REGEX "(^|/)win32dragging[.]cpp$")
list(LENGTH s3g_clipboard_matches s3g_clipboard_match_count)
if(NOT s3g_clipboard_match_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one pinned Windows clipboard source")
endif()
list(REMOVE_ITEM s3g_clipboard_sources ${s3g_clipboard_matches})
list(APPEND s3g_clipboard_sources "${s3g_clipboard_generated}")
set_property(TARGET vstgui PROPERTY SOURCES ${s3g_clipboard_sources})
target_include_directories(vstgui PRIVATE "${vstgui_SOURCE_DIR}/vstgui/lib/platform/win32")
